# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(760, 636)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralWidget)
        self.horizontalLayout.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.mpl_window = QtWidgets.QWidget(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mpl_window.sizePolicy().hasHeightForWidth())
        self.mpl_window.setSizePolicy(sizePolicy)
        self.mpl_window.setMinimumSize(QtCore.QSize(500, 500))
        self.mpl_window.setObjectName("mpl_window")
        self.mpl_vl = QtWidgets.QVBoxLayout(self.mpl_window)
        self.mpl_vl.setContentsMargins(11, 11, 11, 11)
        self.mpl_vl.setSpacing(6)
        self.mpl_vl.setObjectName("mpl_vl")
        self.horizontalLayout.addWidget(self.mpl_window)
        self.button_vl = QtWidgets.QVBoxLayout()
        self.button_vl.setContentsMargins(11, 11, 11, 11)
        self.button_vl.setSpacing(6)
        self.button_vl.setObjectName("button_vl")
        self.button_grid = QtWidgets.QGridLayout()
        self.button_grid.setContentsMargins(11, 11, 11, 11)
        self.button_grid.setSpacing(6)
        self.button_grid.setObjectName("button_grid")
        self.btn_closed = QtWidgets.QPushButton(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_closed.sizePolicy().hasHeightForWidth())
        self.btn_closed.setSizePolicy(sizePolicy)
        self.btn_closed.setMaximumSize(QtCore.QSize(16777215, 25))
        self.btn_closed.setObjectName("btn_closed")
        self.button_grid.addWidget(self.btn_closed, 4, 2, 1, 1)
        self.sb_integration_time = QtWidgets.QSpinBox(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sb_integration_time.sizePolicy().hasHeightForWidth())
        self.sb_integration_time.setSizePolicy(sizePolicy)
        self.sb_integration_time.setMaximumSize(QtCore.QSize(16777215, 25))
        self.sb_integration_time.setObjectName("sb_integration_time")
        self.button_grid.addWidget(self.sb_integration_time, 1, 2, 1, 1)
        self.btn_set_roi = QtWidgets.QPushButton(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_set_roi.sizePolicy().hasHeightForWidth())
        self.btn_set_roi.setSizePolicy(sizePolicy)
        self.btn_set_roi.setMaximumSize(QtCore.QSize(16777215, 25))
        self.btn_set_roi.setObjectName("btn_set_roi")
        self.button_grid.addWidget(self.btn_set_roi, 4, 1, 1, 1)
        self.lbl_integration_time = QtWidgets.QLabel(self.centralWidget)
        self.lbl_integration_time.setObjectName("lbl_integration_time")
        self.button_grid.addWidget(self.lbl_integration_time, 0, 2, 1, 1)
        self.btn_full_frame = QtWidgets.QPushButton(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_full_frame.sizePolicy().hasHeightForWidth())
        self.btn_full_frame.setSizePolicy(sizePolicy)
        self.btn_full_frame.setMaximumSize(QtCore.QSize(16777215, 25))
        self.btn_full_frame.setObjectName("btn_full_frame")
        self.button_grid.addWidget(self.btn_full_frame, 3, 1, 1, 1)
        self.btn_sub_frame = QtWidgets.QPushButton(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_sub_frame.sizePolicy().hasHeightForWidth())
        self.btn_sub_frame.setSizePolicy(sizePolicy)
        self.btn_sub_frame.setMaximumSize(QtCore.QSize(16777215, 25))
        self.btn_sub_frame.setObjectName("btn_sub_frame")
        self.button_grid.addWidget(self.btn_sub_frame, 3, 2, 1, 1)
        self.rad_roi_status = QtWidgets.QRadioButton(self.centralWidget)
        self.rad_roi_status.setObjectName("rad_roi_status")
        self.button_grid.addWidget(self.rad_roi_status, 0, 1, 1, 1)
        self.rad_closed_status = QtWidgets.QRadioButton(self.centralWidget)
        self.rad_closed_status.setObjectName("rad_closed_status")
        self.button_grid.addWidget(self.rad_closed_status, 1, 1, 1, 1)
        self.button_vl.addLayout(self.button_grid)
        self.btn_abort = QtWidgets.QPushButton(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_abort.sizePolicy().hasHeightForWidth())
        self.btn_abort.setSizePolicy(sizePolicy)
        self.btn_abort.setObjectName("btn_abort")
        self.button_vl.addWidget(self.btn_abort)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.button_vl.addItem(spacerItem)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setContentsMargins(11, 11, 11, 11)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textBrowser_2.sizePolicy().hasHeightForWidth())
        self.textBrowser_2.setSizePolicy(sizePolicy)
        self.textBrowser_2.setMaximumSize(QtCore.QSize(16777215, 25))
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.gridLayout.addWidget(self.textBrowser_2, 0, 0, 1, 1)
        self.textBrowser = QtWidgets.QTextBrowser(self.centralWidget)
        self.textBrowser.setObjectName("textBrowser")
        self.gridLayout.addWidget(self.textBrowser, 0, 1, 1, 1)
        self.textBrowser_3 = QtWidgets.QTextBrowser(self.centralWidget)
        self.textBrowser_3.setObjectName("textBrowser_3")
        self.gridLayout.addWidget(self.textBrowser_3, 1, 0, 1, 1)
        self.textBrowser_4 = QtWidgets.QTextBrowser(self.centralWidget)
        self.textBrowser_4.setObjectName("textBrowser_4")
        self.gridLayout.addWidget(self.textBrowser_4, 1, 1, 1, 1)
        self.button_vl.addLayout(self.gridLayout)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.button_vl.addItem(spacerItem1)
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.centralWidget)
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.button_vl.addWidget(self.plainTextEdit)
        self.horizontalLayout.addLayout(self.button_vl)
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 760, 21))
        self.menuBar.setObjectName("menuBar")
        MainWindow.setMenuBar(self.menuBar)
        self.mainToolBar = QtWidgets.QToolBar(MainWindow)
        self.mainToolBar.setObjectName("mainToolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "EXPRES FTT"))
        self.btn_closed.setText(_translate("MainWindow", "Closed"))
        self.btn_set_roi.setText(_translate("MainWindow", "ROI"))
        self.lbl_integration_time.setText(_translate("MainWindow", "Speed"))
        self.btn_full_frame.setText(_translate("MainWindow", "Full Frame"))
        self.btn_sub_frame.setText(_translate("MainWindow", "Sub Frame"))
        self.rad_roi_status.setText(_translate("MainWindow", "Loop Closed"))
        self.rad_closed_status.setText(_translate("MainWindow", "ROI Up-to-date"))
        self.btn_abort.setText(_translate("MainWindow", "Abort"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

